bet_Integrase_Zn__rve = [ 1482, 1490,]
bef_RVP = [ 441, 765,]
bet_RVP__RVT_1 = [ 861, 925,]
aft_IN_DBD_C = [ 1708, 1727,]
bet_RVT_connect__RNase_H = [ 1296, 1311,]
bet_RNase_H__Integrase_Zn = [ 1434, 1443,]
bet_RVT_thumb__RVT_connect = [ 1176, 1188,]
bet_rve__IN_DBD_C = [ 1598, 1657,]
p6-pol = [ 441, 761,]
